### PR TITLE
Disable debug on console calls to yiic.

### PR DESCRIPTION
**Pull request by Medalink**

### CODE REVIEW

**Comment by Medalink** [comment]
This prevents errors on console calls where the toolbar is loaded. Since the debug toolbar is not compatible with the CLI this PR will disable it from loading under a CLI env.

**Comment by Medalink** [comment]
Any updates on this? Questions or comments?

**Comment by Medalink** [comment]
I found a work-around without this PR.

```php
'debug' => array(
	'class' => 'vendor.zhuravljov.yii2-debug.Yii2Debug',
	'accessExpression' => '!Yii::app() instanceof CConsoleApplication',
),
```

**Comment by Medalink** [comment]
Nevermind, this still blows up my command's that use CURL... any idea on how I can completely disable this component on CLI when I can not use two separate config files?

**Comment by zhuravljov** [comment]
Thanks

**Pull request merged**
